### ISSUE TITLE
关于某些模组

### ISSUE THREAD

**Issue by StarPrimary** [moguang2004/Create-New-Horizon#1]
说实话[gpumemleakfix](https://github.com/moguang2004/Create-New-Horizon/blob/main/mods/gpumemleakfix-1.20.1-1.8.jar)和[memoryleakfix](https://github.com/moguang2004/Create-New-Horizon/blob/main/mods/memoryleakfix-forge-1.17%2B-1.1.5.jar)其实没啥软用。相反，gpu泄露修复这个自身可能还存在问题。

[sereneseasonfix](https://github.com/moguang2004/Create-New-Horizon/blob/main/mods/sereneseasonfix-1.20.1-1.0.8.jar)也没啥加的必要，目前在几个加了静谧四季的整合包中并没有发现模组作者说的问题，相反这个模组可能会导致出现其他问题。

gtnh没联动暮色，而且暮色内容也过于老旧，我个人认为没有加的必要。
(只是个意见，如果您有啥想法那当然可以忽略这条)

**Comment by moguang2004** [comment]
感谢你的反馈！这几个优化模组我再测试过后会考虑删除或者保留，至于暮色森林算是给老玩家们留的一些记忆吧，之后也会考虑添加更多暮色森林和主线的联系，咱也不必啥都必须得和gtnh一样，可以搞出一些不一样的玩法。

**Comment by StarPrimary** [comment]
好的，感谢您的回复。
