### ISSUE TITLE
无中生有?

### ISSUE THREAD

**Issue by creepebucket** [moguang2004/Create-New-Horizon#3]
![image](https://github.com/user-attachments/assets/6e56e16b-a74e-4450-9588-322361bb6083)
为什么铁锯能无中生有出天根木板啊喂
真就 天 根

**Comment by creepebucket** [comment]
啊?

**Comment by CPearl0** [comment]
Fixed in https://github.com/moguang2004/Create-New-Horizon/commit/a9d0f5af159847542f1442f01d3bb274d36e94f2
