### ISSUE TITLE
关于损坏的体温维持器

### ISSUE THREAD

**Issue by aaron-yang2009** [moguang2004/Create-New-Horizon#4]
初始任务送的体温维持器耐久会降到负数导致永远不会损坏（如下图），并且耐久为负时其功能仍然能够生效
![2024-09-02_14 12 03](https://github.com/user-attachments/assets/1cbfe743-6c86-4a24-a70c-c4fa48b72f65)

**Comment by moguang2004** [comment]
新版已修复
