### ISSUE TITLE
1.08c [机械动力-冲压机] 小型青铜流体管道无法用机械动力冲压机配方合成

### ISSUE THREAD

**Issue by awt000** [moguang2004/Create-New-Horizon#63]
跟着任务线走的
1.机械动力-车床，配方里凹陷冲压头和凸陷冲压头是反着出的，配方选凹陷出凸显，先凸出凹。
2.冲压机配方，放青铜板上去，冲压机没反应，跟着任务线走无法做出小型青铜流体管道。

**Comment by you-xia-xue** [comment]
我修了
