### ISSUE TITLE
1.08c 沉浸飞行 望远镜 无法合成

### ISSUE THREAD

**Issue by YELANDAOKONG** [moguang2004/Create-New-Horizon#64]
此问题在1.07d/1.08c均存在

如图所示：

![image](https://github.com/user-attachments/assets/496bc2b3-6841-45f3-9943-e438ca811591)
![image](https://github.com/user-attachments/assets/40ebf055-5de9-4070-b309-878463979f47)

这两个不同物品的配方，一开始都是双层铜板+工业齿轮，可能存在冲突，生存模式无法正常合成；
合成只会得到这种东西：

![image](https://github.com/user-attachments/assets/db5375d8-2a11-40fd-94b2-1d9227793e59)

这导致只能合成“旋转炮”，“望远镜”永远无法合成

**Comment by moguang2004** [comment]
108d已修复
