### ISSUE TITLE
希望机械动力对安山合金的增产加强

### ISSUE THREAD

**Issue by you-xia-xue** [moguang2004/Create-New-Horizon#72]
![image](https://github.com/user-attachments/assets/e55800be-6131-41ea-97c7-67612553f2f3)
把对铁熔炼超级加热改成普通加热
![image](https://github.com/user-attachments/assets/cea3f8df-0d65-4b6b-aab1-8a3c4da7a2c0)

**Comment by you-xia-xue** [comment]
我自己改了

**Comment by moguang2004** [comment]
Complete in #76
